### ISSUE TITLE
Create stations for data

### ISSUE THREAD

**Issue by cedricbriandgithub** [ices-eg/WGEEL#6]
We will probably need a bulk load of the stations.
I need help to write the right organization, see script below the table

| tblCodeID | Station_Code | Country       | Organisation | Station_Name | WLTYP |      Lat |      Lon | StartYear | EndYear | PURPM   | Notes |
|----------:|-------------:|---------------|--------------|--------------|-------|---------:|---------:|----------:|--------:|---------|-------|
|    170000 |        12000 | FRANCE        | NA           | AdTC         | NA    | 43.48000 | -1.44000 |      1986 |    2008 | S\~T    | NA    |
|    170001 |        12001 | FRANCE        | NA           | AdCP         | NA    | 43.48000 | -1.44000 |      1928 |    2008 | S\~T    | NA    |
|    170002 |        12002 | SPAIN         | NA           | Albu         | NA    | 39.31000 | -0.30000 |      1949 |      NA | S\~T    | NA    |
|    170003 |        12003 | SPAIN         | NA           | AlCP         | NA    | 39.31000 | -0.30000 |      1982 |      NA | S\~T    | NA    |
|    170004 |        12004 | GREAT BRITAIN | NA           | Bann         | NA    | 55.12000 | -6.42000 |      1960 |      NA | S\~T    | NA    |
|    170005 |        12005 | FRANCE        | NA           | Bres         | NA    | 50.05000 |  1.42000 |      1994 |      NA | S\~T    | NA    |
|    170006 |        12006 | SWEDEN        | NA           | Dala         | NA    | 60.18000 | 16.60000 |      1951 |      NA | S\~T    | NA    |
|    170007 |        12007 | SPAIN         | NA           | Ebro         | NA    | 40.72000 |  0.76000 |      1966 |      NA | S\~T    | NA    |
|    170008 |        12008 | GERMANY       | NA           | Ems          | NA    | 53.02000 |  7.20000 |      1946 |    2001 | S\~T    | NA    |
|    170009 |        12009 | IRELAND       | NA           | Erne         | NA    | 54.30000 | -8.15000 |      1959 |      NA | S\~T    | NA    |
|    170010 |        12010 | FRANCE        | NA           | Fre          | NA    | 48.57316 | -2.09479 |      1997 |      NA | S\~T    | NA    |
|    170011 |        12011 | FRANCE        | NA           | GiTC         | NA    | 45.40000 | -0.80000 |      1923 |    2008 | S\~T    | NA    |
|    170012 |        12012 | FRANCE        | NA           | GiCP         | NA    | 45.40000 | -0.80000 |      1961 |    2008 | S\~T    | NA    |
|    170013 |        12013 | FRANCE        | NA           | GiSc         | NA    | 45.40000 | -0.80000 |      1992 |      NA | S\~T    | NA    |
|    170014 |        12014 | SWEDEN        | NA           | Gota         | NA    | 58.02000 | 12.12000 |      1900 |      NA | S\~T    | NA    |
|    170015 |        12015 | DENMARK       | NA           | Gude         | NA    | 56.35000 |  9.60000 |      1980 |    2014 | S\~T    | NA    |
|    170016 |        12016 | DENMARK       | NA           | Hart         | NA    | 55.51000 |  9.41000 |      1967 |      NA | S\~T    | NA    |
|    170017 |        12017 | BELGIUM       | NA           | Yser         | NA    | 51.08000 |  2.45000 |      1964 |      NA | S\~T    | NA    |
|    170018 |        12018 | NORWAY        | NA           | Imsa         | NA    | 58.54000 |  5.59000 |      1975 |      NA | S\~T    | NA    |
|    170019 |        12019 | SWEDEN        | NA           | YFS1         | NA    | 57.00000 |  5.00000 |      1975 |    1989 | F\~S\~T | NA    |
|    170020 |        12020 | SWEDEN        | NA           | YFS2         | NA    | 57.00000 |  5.00000 |      1991 |      NA | F\~S\~T | NA    |
|    170021 |        12021 | NETHERLANDS   | NA           | Katw         | NA    | 52.21000 |  4.40000 |      1977 |      NA | S\~T    | NA    |
|    170022 |        12022 | SWEDEN        | NA           | Kavl         | NA    | 55.78000 | 13.10000 |      1992 |      NA | S\~T    | NA    |
|    170023 |        12023 | DENMARK       | NA           | Klit         | NA    | 57.04000 |  8.49000 |      2008 |      NA | S\~T    | NA    |
|    170024 |        12024 | SWEDEN        | NA           | Laga         | NA    | 56.54532 | 12.95349 |      1925 |      NA | S\~T    | NA    |
|    170025 |        12025 | NETHERLANDS   | NA           | Lauw         | NA    | 53.40000 |  6.19000 |      1976 |      NA | S\~T    | NA    |
|    170026 |        12026 | FRANCE        | NA           | Loi          | NA    | 47.28000 | -1.96000 |      1924 |    2008 | S\~T    | NA    |
|    170027 |        12027 | BELGIUM       | NA           | Meus         | NA    | 50.75000 |  5.67000 |      1992 |      NA | S\~T    | NA    |
|    170028 |        12028 | PORTUGAL      | NA           | MiPo         | NA    | 41.90000 | -8.81000 |      1975 |      NA | S\~T    | NA    |
|    170029 |        12029 | SPAIN         | NA           | MiSp         | NA    | 41.90000 | -8.81000 |      1975 |      NA | S\~T    | NA    |
|    170030 |        12030 | SWEDEN        | NA           | Morr         | NA    | 56.40000 | 14.66000 |      1960 |      NA | S\~T    | NA    |
|    170031 |        12031 | SWEDEN        | NA           | Mota         | NA    | 58.58000 | 16.17000 |      1942 |      NA | S\~T    | NA    |
|    170032 |        12032 | SPAIN         | NA           | Nalo         | NA    | 43.55000 | -6.08000 |      1953 |      NA | S\~T    | NA    |
|    170033 |        12033 | DENMARK       | NA           | Nors         | NA    | 57.04800 |  8.51000 |      2008 |      NA | S\~T    | NA    |
|    170034 |        12034 | NETHERLANDS   | NA           | RhDO         | NA    | 52.40000 |  5.25000 |      1938 |      NA | S\~T    | NA    |
|    170035 |        12035 | NETHERLANDS   | NA           | RhIj         | NA    | 52.46000 |  4.60000 |      1969 |      NA | S\~T    | NA    |
|    170036 |        12036 | SWEDEN        | NA           | Ring         | NA    | 57.15000 | 12.07000 |      1981 |      NA | S\~T    | NA    |
|    170037 |        12037 | IRELAND       | NA           | Feal         | NA    | 52.47000 | -9.63000 |      1985 |      NA | S\~T    | NA    |
|    170038 |        12038 | IRELAND       | NA           | Inag         | NA    | 52.83000 | -9.43000 |      1996 |      NA | S\~T    | NA    |
|    170039 |        12039 | IRELAND       | NA           | Maig         | NA    | 52.65000 | -8.78000 |      1994 |      NA | S\~T    | NA    |
|    170040 |        12040 | SWEDEN        | NA           | Ronn         | NA    | 55.10000 | 14.70000 |      1946 |      NA | S\~T    | NA    |
|    170041 |        12041 | GREAT BRITAIN | NA           | SeEA         | NA    | 51.67000 | -2.56000 |      1972 |      NA | S\~T    | NA    |
|    170042 |        12042 | GREAT BRITAIN | NA           | SeHM         | NA    | 51.67000 | -2.56000 |      1979 |      NA | S\~T    | NA    |
|    170043 |        12043 | FRANCE        | NA           | SevN         | NA    | 46.31000 | -1.07000 |      1962 |    2008 | S\~T    | NA    |
|    170044 |        12044 | IRELAND       | NA           | ShaA         | NA    | 52.42000 | -8.36000 |      1977 |      NA | S\~T    | NA    |
|    170045 |        12045 | IRELAND       | NA           | ShaP         | NA    | 52.60000 | -8.62000 |      1985 |      NA | S\~T    | NA    |
|    170046 |        12046 | DENMARK       | NA           | Sle          | NA    | 57.15000 |  9.35000 |      2008 |      NA | S\~T    | NA    |
|    170047 |        12047 | NETHERLANDS   | NA           | Stel         | NA    | 51.83000 |  4.03000 |      1971 |      NA | S\~T    | NA    |
|    170048 |        12048 | ITALY         | NA           | Tibe         | NA    | 41.44000 | 12.14000 |      1975 |    2006 | S\~T    | NA    |
|    170049 |        12049 | DENMARK       | NA           | Vida         | NA    | 55.58000 |  8.40000 |      1971 |    1990 | S\~T    | NA    |
|    170050 |        12050 | FRANCE        | NA           | Vil          | NA    | 47.50000 | -2.39000 |      1971 |      NA | S\~T    | NA    |
|    170051 |        12051 | SWEDEN        | NA           | Visk         | NA    | 57.12000 | 12.07000 |      1972 |      NA | S\~T    | NA    |

I need someone to help with this : replace NULL by organization names.
-------------------------------
```sql
update ref.tr_station set "Organisation"=NULL where "Station_Name"='YFS1';
update ref.tr_station set "Organisation"=NULL where "Station_Name"='Ring';
update ref.tr_station set "Organisation"=NULL where "Station_Name"='Visk';
update ref.tr_station set "Organisation"=NULL where "Station_Name"='Bann';
update ref.tr_station set "Organisation"=NULL where "Station_Name"='Erne';
update ref.tr_station set "Organisation"=NULL where "Station_Name"='ShaA';
update ref.tr_station set "Organisation"=NULL where "Station_Name"='SeEA';
update ref.tr_station set "Organisation"=NULL where "Station_Name"='SeHM';
update ref.tr_station set "Organisation"=NULL where "Station_Name"='Vida';
update ref.tr_station set "Organisation"='LAVES' where "Station_Name"='Ems';
update ref.tr_station set "Organisation"=NULL where "Station_Name"='Lauw';
update ref.tr_station set "Organisation"=NULL where "Station_Name"='RhDO';
update ref.tr_station set "Organisation"=NULL where "Station_Name"='RhIj';
update ref.tr_station set "Organisation"=NULL where "Station_Name"='Katw';
update ref.tr_station set "Organisation"=NULL where "Station_Name"='Stel';
update ref.tr_station set "Organisation"=NULL where "Station_Name"='Yser';
update ref.tr_station set "Organisation"='EPTB-Vilaine' where "Station_Name"='Vil';
update ref.tr_station set "Organisation"='IFREMER' where "Station_Name"='Loi';
update ref.tr_station set "Organisation"='Agrocampus Ouest' where "Station_Name"='SevN';
update ref.tr_station set "Organisation"='IRSTEA' where "Station_Name"='GiTC';
update ref.tr_station set "Organisation"='IRSTEA' where "Station_Name"='GiCP';
update ref.tr_station set "Organisation"='IFREMER' where "Station_Name"='AdTC';
update ref.tr_station set "Organisation"=NULL where "Station_Name"='AdCP';
update ref.tr_station set "Organisation"=NULL where "Station_Name"='Nalo';
update ref.tr_station set "Organisation"=NULL where "Station_Name"='Albu';
update ref.tr_station set "Organisation"=NULL where "Station_Name"='MiSp';
update ref.tr_station set "Organisation"=NULL where "Station_Name"='MiPo';
update ref.tr_station set "Organisation"=NULL where "Station_Name"='Tibe';
update ref.tr_station set "Organisation"=NULL where "Station_Name"='Imsa';
update ref.tr_station set "Organisation"=NULL where "Station_Name"='Dala';
update ref.tr_station set "Organisation"=NULL where "Station_Name"='Mota';
update ref.tr_station set "Organisation"=NULL where "Station_Name"='Morr';
update ref.tr_station set "Organisation"=NULL where "Station_Name"='Kavl';
update ref.tr_station set "Organisation"=NULL where "Station_Name"='Ronn';
update ref.tr_station set "Organisation"=NULL where "Station_Name"='Laga';
update ref.tr_station set "Organisation"=NULL where "Station_Name"='Gota';
update ref.tr_station set "Organisation"=NULL where "Station_Name"='ShaP';
update ref.tr_station set "Organisation"=NULL where "Station_Name"='Gude';
update ref.tr_station set "Organisation"=NULL where "Station_Name"='Hart';
update ref.tr_station set "Organisation"=NULL where "Station_Name"='Meus';
update ref.tr_station set "Organisation"=NULL where "Station_Name"='YFS2';
update ref.tr_station set "Organisation"='IRSTEA' where "Station_Name"='GiSc';
update ref.tr_station set "Organisation"=NULL where "Station_Name"='Ebro';
update ref.tr_station set "Organisation"=NULL where "Station_Name"='AlCP';
update ref.tr_station set "Organisation"=NULL where "Station_Name"='Feal';
update ref.tr_station set "Organisation"=NULL where "Station_Name"='Maig';
update ref.tr_station set "Organisation"=NULL where "Station_Name"='Inag';
update ref.tr_station set "Organisation"='AFB' where "Station_Name"='Bres';
update ref.tr_station set "Organisation"='MNHN' where "Station_Name"='Fre';
update ref.tr_station set "Organisation"=NULL where "Station_Name"='Sle';
update ref.tr_station set "Organisation"=NULL where "Station_Name"='Klit';
update ref.tr_station set "Organisation"=NULL where "Station_Name"='Nors';

```

**Comment by jdpo** [comment]
update ref.tr_station set "Organisation"='LAVES' where "Station_Name"='Ems';

**Comment by LBeaulaton** [comment]
update ref.tr_station set "Organisation"='AFB' where "Station_Name"='Bres';

**Comment by cedricbriandgithub** [comment]
solved by Patrick and group 2
